export const FETCH_FOLLOWERS_FOLLOWINGS = "FETCH_FOLLOWERS_FOLLOWINGS";
export const FETCHED_FOLLOWERS_FOLLOWINGS = "FETCHED_FOLLOWERS_FOLLOWINGS";
export const FAILED_FETCH = "FAILED_FETCH";
export const FIND_TRAITORS = "FIND_TRAITORS";
export const CHANGE_USERLIST_TAB = "CHANGE_USERLIST_TAB";